[build-system]
requires = [
    "wheel",
    "setuptools<60",
    "oldest-supported-numpy",
    "setuptools-git-versioning",
]
# the recommended "build_meta" does not work with nonstop f2py and hence is commented out
# build-backend = "setuptools.build_meta"


[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dev_template = "{tag}.post{ccount}"
# ignore "dirty" flag when building using CI for windows: seems to be a bug in the versioning tool
dirty_template = "{tag}"
# version_callback = "setup:get_version"

[tool.cibuildwheel]
# skip 32-bit and pypy builds
skip = ["*-win32", "*-manylinux_i686", "pp*", '*-musllinux*']
# build-frontend = "pip"
before-build = ["git describe --tags --always --dirty"]

# Increase pip debugging output
build-verbosity = 0

test-requires = "pytest"
test-command = 'pytest -s "{package}/supy_driver/test"'


[tool.cibuildwheel.linux]
# Install system library
before-all = ["yum install -y glibc-static", "make suews"]
archs = ["auto64"]

[tool.cibuildwheel.macos]
before-all = [
    'ln -sf "$(which gfortran-10)" /usr/local/bin/gfortran',
    "make suews",
]
archs = ["auto64","arm64"]
skip = ['*cp311*','pp*']
build-verbosity = 10


[tool.cibuildwheel.windows]
before-all = ["make suews"]
before-build = [
    "cd {package}",
    "python -m pip install numpy",
    "python build-win-def.py",
    "git status",
    # "python -m pip install delvewheel"
]
archs = ["auto64"]
# repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"
