[build-system]
requires = [
    "wheel",
    "setuptools<60",
    "oldest-supported-numpy",
    'versioningit',
]
# the recommended "build_meta" does not work with nonstop f2py and hence is commented out
# build-backend = "setuptools.build_meta"

# add some dirty stuff to make sure that the build system is not confused by the
# [tool.setuptools-git-versioning]
# enabled = true
# template = "2022.{tag}"
# dev_template = "{tag}.post{ccount}"
# # ignore "dirty" flag when building using CI
# dirty_template = "{tag}.post{ccount}"
[tool.versioningit.vcs]
# The method key:
method = "git"  # <- The method name

# Parameters to pass to the method:
match = ["20*"]
# default-tag = "0.0.0"

[tool.versioningit.format]

# Format used when there have been commits since the most recent tag:
distance = "{base_version}.post{distance}+{vcs}{rev}+test"

# Format used when there are uncommitted changes:
dirty = "{base_version}+d{build_date:%Y%m%d}+test"

# Format used when there are both commits and uncommitted changes:
distance-dirty = "{base_version}.post{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.versioningit.write]
file = "supy_driver/version.py"


[tool.cibuildwheel]
# skip 32-bit and pypy builds
# skip = ["*-win32", "*-manylinux_i686", "pp*", '*-musllinux*']
# build-frontend = "pip"
before-build = ["git describe --tags --always --dirty"]

# Increase pip debugging output
build-verbosity = 0

test-requires = "pytest"
test-command = "pytest -s {package}/supy_driver/test"


[tool.cibuildwheel.linux]
# Install system library
before-all = ["yum install -y glibc-static", "make suews"]
archs = ["auto64"]

[tool.cibuildwheel.macos]
before-all = [
    'ln -sf "$(which gfortran-10)" /usr/local/bin/gfortran',
    "make suews",
]
build = ['cp39*']


[tool.cibuildwheel.windows]
before-all = ["make suews"]
before-build = [
    "cd {package}",
    "python -m pip install numpy",
    "python build-win-def.py",
]
archs = ["auto64"]
