# yaml-language-server: $schema=../suews-var-def.json
# use the above definition to enable schema validation in VSCode

# NB: This file is manually curated by the SUEWS development team and is used in the following places:
# - SUEWS documentation: https://suews.readthedocs.io/en/latest/variables.html
# - SUEWS variable json schema file to enable schema validation (via `convert_var_info_to_json_schema.py` in this repo)
# any questions, please contact the SUEWS development team by submitting an issue:
# https://github.com/UMEP-dev/SUEWS/issues/new

# #########################################################################
# this file is used to define:
#  variables used in describing site properties
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# revision history:
# TS 08 Mar 2023: checked
# #########################################################################

# essential site properties

- name: lat
  use:
    input: parameter
  description: Latitude
  dimensions: 0
  unit: deg
  # suews table headers: :option:`lat <suews:lat>`
  requisite:
    site description

- name: lng
  use:
    input: parameter
  description: longitude
  dimensions: 0
  unit: deg
  suews table headers: :option:`lng <suews:lng>`
  requisite:
    site description

- name: alt
  use:
    input: parameter
  description: Altitude of grids
  dimensions: 0
  unit: m
  suews table headers: :option:`Alt <suews:Alt>`
  requisite:
    site description

- name: timezone
  use:
    input: parameter
  description: Time zone. This should be set accordingto the times given in the meteorological forcing file(s)
  dimensions: 0
  unit: h
  suews table headers: :option:`Timezone <suews:Timezone>`
  requisite:
    site description

- name: surfacearea
  use:
    input: parameter
  description: Area of the grid
  dimensions: 0
  unit: ha
  suews table headers: :option:`SurfaceArea <suews:SurfaceArea>`
  requisite:
    site description

- name: sfr_surf # split into land cover based scalars?
  use:
    input: parameter
  description: Surface cover fractions.
  dimensions:
    7: "SUEWS land covers: { Paved`, Bldgs`, EveTr`, DecTr`, Grass`, BSoil`, Water`}"
  unit: "-"
  suews table headers:
    :option:`Fr_Bldgs <suews:Fr_Bldgs>`, :option:`Fr_Bsoil <suews:Fr_Bsoil>`,
    :option:`Fr_DecTr <suews:Fr_DecTr>`, :option:`Fr_EveTr <suews:Fr_EveTr>`, :option:`Fr_Grass
    <suews:Fr_Grass>`, :option:`Fr_Paved <suews:Fr_Paved>`, :option:`Fr_Water <suews:Fr_Water>`
  requisite:
    site description

- name: z
  use:
    input: parameter
  description: Measurement height for all atmospheric forcing variables set in the meteorological forcing file `SSss_YYYY_data_tt.txt`
  dimensions: 0
  unit: m
  suews table headers: :option:`z <suews:z>`
  requisite:
    site description

- name: z0m_in
  use:
    input: parameter
  description: Roughness length for momentum
  dimensions: 0
  unit: m
  suews table headers: :option:`z0 <suews:z0>`
  requisite:
    RoughLenMomMethod: 1:provided

- name: zdm_in
  use:
    input: parameter
  description: Zero-plane displacement
  dimensions: 0
  unit: m
  suews table headers: :option:`zd <suews:zd>`
  requisite:
    RoughLenMomMethod: 1:provided

# surface fraction of automated irrigation
- name: faut
  use:
    input: parameter
  description: Fraction of irrigated area that is irrigated using automated systems
  dimensions: 0
  unit: "-"
  suews table headers: :option:`Faut <suews:Faut>`
  requisite:
    WaterUseMethod.0_modelled

# day light savings
- name: startdls
  use:
    input: parameter
  description: Start of the day light savings
  dimensions: 0
  unit: DOY
  suews table headers: :option:`StartDLS <suews:StartDLS>`
  requisite:
    daylightsavings: .nan

- name: enddls
  use:
    input: parameter
  description: End of the day light savings
  dimensions: 0
  unit: DOY
  suews table headers: :option:`EndDLS <suews:EndDLS>`
  requisite:
    daylightsavings - all human activities: NEW Option Automatic via Python Package or provide

# land cover properties
# FAI: frontal area index
- name: faibldg # todo rename to fai_bldgs
  use:
    input: parameter
  description: Frontal area index for buildings
  dimensions: 0
  unit: "-"
  suews table headers: :option:`FAI_Bldgs <suews:FAI_Bldgs>`
  requisite:
    RoughLenMomMethod: "3: MacDonald"

- name: faidectree # todo rename to fai_dectr
  use:
    input: parameter
  description: Frontal area index for deciduous trees
  dimensions: 0
  unit: "-"
  suews table headers: :option:`FAI_DecTr <suews:FAI_DecTr>`
  requisite:
    RoughLenMomMethod: "3: MacDonald"

- name: faievetree # todo rename to fai_evetr
  use:
    input: parameter
  description: Frontal area index for evergreen trees
  dimensions: 0
  unit: "-"
  suews table headers: :option:`FAI_EveTr <suews:FAI_EveTr>`
  requisite:
    RoughLenMomMethod: "3: MacDonald"

# mean height of roughness elements
- name: dectreeh # todo: rename to h_dectr
  use:
    input: parameter
  description: Mean height of deciduous trees
  dimensions: 0
  unit: m
  suews table headers: :option:`H_DecTr <suews:H_DecTr>`
  requisite:
    site description

- name: evetreeh # todo: rename to h_evetr
  use:
    input: parameter
  description: Mean height of evergreen trees
  dimensions: 0
  unit: m
  suews table headers: :option:`H_EveTr <suews:H_EveTr>`
  requisite:
    site description

- name: bldgh # todo: rename to h_bldgs
  use:
    input: parameter
  description: Mean building height
  dimensions: 0
  unit: m
  suews table headers: :option:`H_Bldgs <suews:H_Bldgs>`
  requisite:
    site description

# porosity
- name: pormax_dec
  use:
    input: parameter
  description:
    full leaf-on summertime value Used only for `DecTr` (can affect roughness
    calculation)
  dimensions: 0
  unit: "-"
  suews table headers: :option:`PorosityMax <suews:PorosityMax>`
  requisite:
    RoughLenMomMethod: ALL

- name: pormin_dec
  use:
    input: parameter
  description:
    leaf-off wintertime value Used only for `DecTr` (can affect roughness
    calculation)
  dimensions: 0
  unit: "-"
  suews table headers: :option:`PorosityMin <suews:PorosityMin>`
  requisite:
    RoughLenMomMethod: ALL

- name: porosity_id
  use:
    input: state
  description: Porosity of deciduous vegetation on day 0 of run.
  dimensions: 0
  unit: "-"
  suews table headers: :option:`porosity0 <suews:porosity0>`
  requisite:
    RoughLenMomMethod: ALL
