# this is a sample config file for suews simulations
# suitable for versions >= 2023.5

- name: london sim
- description: london sim
- model:
  - control:
    - tstep: 300
    - forcing_file: london_2016_2017.csv
    - output_file: london_2016_2017_output.csv
    - daylightsaving_method: 1
  - physics:
    - netradiationmethod: 1
    - emissionsmethod: 1
    - storageheatmethod: 1
    - aerodynamicresistancemethod: 1
    - roughlenmommethod: 1
    - roughlenheatmethod: 1
    - stabilitymethod: 1
    - smdmethod: 1
    - waterusemethod: 1
    - diagmethod: 1
    - snowuse: 0

- site:
  - name: london
  - lat: 51.5074
  - lon: 0.1278
  - land cover:
    - decidous trees:
      - several properties
    - evergreen trees:
      - several properties
    - grass:
      - several properties
    - water:
      - several properties
    - buildings:
      - several properties
    - paved:
      - several properties
  -

