# this is a sample config file for suews simulations
# suitable for versions >= 2023.5

- name: london sim
- description: london sim
- model:
  - control:
    - tstep: 300
    - forcing_file: london_2016_2017.csv
    - output_file: london_2016_2017_output.csv
    - daylightsaving_method: 1
  - physics:
    - netradiationmethod: 1
    - emissionsmethod: 1
    - storageheatmethod: 1
    - aerodynamicresistancemethod: 1
    - roughlenmommethod: 1
    - roughlenheatmethod: 1
    - stabilitymethod: 1
    - smdmethod: 1
    - waterusemethod: 1
    - diagmethod: 1
    - snowuse: 0

- site:
  - name: london
  - properties:
    - lat: 51.5074
    - lon: 0.1278
    - pipecapacity: 100
    - runofftowater: 0.5
    - raincover: 0.5
    - rainmaxres: 0.5
    - drainrt: 0.5
    - veg_type: 1
    - land cover:
      - paved:
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracpaved: 0.5
        - wetthresh: 0.5
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_bldgs: 0.1
          - to_dectr: 0.1
          - to_evetr: 0.1
          - to_grass: 0.1
          - to_bsoil: 0.1
          - to_water: 0.1
          - to_runoff: 0.4
      - bldgs: # buildings
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracbldgs: 0.5
        - wetthresh: 0.5
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_paved: 0.1
          - to_dectr: 0.1
          - to_evetr: 0.1
          - to_grass: 0.1
          - to_bsoil: 0.1
          - to_water: 0.1
          - to_runoff: 0.4
      - dectr: # deciduous trees
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - statelimit: 10
        - capmax_dec: 100
        - capmin_dec: 10
        - irrfracdectr: 0.5
        - sathydraulicconduct: 0.5
        - wetthresh: 0.5
        - beta_bioco2: 0.5
        - beta_enh_bioco2: 0.5
        - alpha_bioco2: 0.5
        - alpha_enh_bioco2: 0.5
        - resp_a: 0.5
        - resp_b: 0.5
        - theta_bioco2: 0.5
        - conductance:
          - g_max: 200
          - g_k: 100
          - g_q_base: 12
          - g_q_shape: 2
          - g_t: 20
          - g_sm: 200
          - kmax: 1200
          - gsmodel: 1
          - maxconductance: 20
          - s1: 0.5
          - s2: 0.5
        - lai:
          - baset: 20
          - gddfull: 100
          - basete: 15
          - sddfull: 100
          - laimin: 0.1
          - laimax: 2
          - laipower: 2
          - laitype: 1
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5 # this is a state and changes with time depending on LAI
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_paved: 0.1
          - to_bldgs: 0.1
          - to_evetr: 0.1
          - to_grass: 0.1
          - to_bsoil: 0.1
          - to_water: 0.1
          - to_soilstore: 0.4
      - evetr: # evergreen trees
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracevetr: 0.5
        - wetthresh: 0.5
        - beta_bioco2: 0.5
        - beta_enh_bioco2: 0.5
        - alpha_bioco2: 0.5
        - alpha_enh_bioco2: 0.5
        - resp_a: 0.5
        - resp_b: 0.5
        - theta_bioco2: 0.5
        - conductance:
          - g_max: 200
          - g_k: 100
          - g_q_base: 12
          - g_q_shape: 2
          - g_t: 20
          - g_sm: 200
          - kmax: 1200
          - gsmodel: 1
          - maxconductance: 20
          - s1: 0.5
          - s2: 0.5
        - lai:
          - baset: 20
          - gddfull: 100
          - basete: 15
          - sddfull: 100
          - laimin: 0.1
          - laimax: 2
          - laipower: 2
          - laitype: 1
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_paved: 0.1
          - to_bldgs: 0.1
          - to_dectr: 0.1
          - to_grass: 0.1
          - to_bsoil: 0.1
          - to_water: 0.1
          - to_soilstore: 0.4
      - grass:
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracgrass: 0.5
        - wetthresh: 0.5
        - beta_bioco2: 0.5
        - beta_enh_bioco2: 0.5
        - alpha_bioco2: 0.5
        - alpha_enh_bioco2: 0.5
        - resp_a: 0.5
        - resp_b: 0.5
        - theta_bioco2: 0.5
        - conductance:
          - g_max: 200
          - g_k: 100
          - g_q_base: 12
          - g_q_shape: 2
          - g_t: 20
          - g_sm: 200
          - kmax: 1200
          - gsmodel: 1
          - maxconductance: 20
          - s1: 0.5
          - s2: 0.5
        - lai:
          - baset: 20
          - gddfull: 100
          - basete: 15
          - sddfull: 100
          - laimin: 0.1
          - laimax: 2
          - laipower: 2
          - laitype: 1
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_paved: 0.1
          - to_bldgs: 0.1
          - to_dectr: 0.1
          - to_evetr: 0.1
          - to_bsoil: 0.1
          - to_water: 0.1
          - to_soilstore: 0.4
      - bsoil: # bare soil
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracbsoil: 0.5
        - wetthresh: 0.5
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        - waterdist: # sum of all values must be 1
          - to_paved: 0.1
          - to_bldgs: 0.1
          - to_dectr: 0.1
          - to_evetr: 0.1
          - to_grass: 0.1
          - to_water: 0.1
          - to_soilstore: 0.4
      - water:
        - soildepth: 0.1
        - soilstore: 100
        - soilstorecap: 200
        - state: 10
        - statelimit: 10
        - sathydraulicconduct: 0.5
        - irrfracwater: 0.5
        - flowchange: 0.5
        - storedrainprm: # for surface water (i.e. above ground)
          - store_min: 0.1
          - store_max: 0.2
          - store_cap: 0.5
          - drain_eq: 1
          - drain_coef_1: 0.5
          - drain_coef_2: 0.5
        # `waterdist` is not needed for water
    - irrigation:
      - h_maintain: 10
      - ie_a: [1,1,1]
      - ie_m: [1,1,1]
      - ie_start: 100
      - ie_end: 200
      - internalwateruse_h: 10
      - daywatper:
        - Monday: 10
        - Tuesday: 10
        - Wednesday: 10
        - Thursday: 10
        - Friday: 10
        - Saturday: 10
        - Sunday: 10
      - daywat:
        - Monday: 10
        - Tuesday: 10
        - Wednesday: 10
        - Thursday: 10
        - Friday: 10
        - Saturday: 10
        - Sunday: 10
    - anthropogenic emissions:
      - heat:
        - qf0_beu:
          - working day: 10
          - holiday: 10
        - qf_a:
          - working day: 10
          - holiday: 10
        - qf_b:
          - working day: 10
          - holiday: 10
        - qf_c:
          - working day: 10
          - holiday: 10
        - baset_cooling:
          - working day: 10
          - holiday: 10
        - baset_heating:
          - working day: 10
          - holiday: 10
        - ah_min: 0.1
        - ah_slope_cooling: 0.1
        - ah_slope_heating: 0.1
        - ahprof_24hr:
          - working day: # 24 hours
            - 1: 0.1
            - 2: 0.1
            - 3: 0.1
            - 4: 0.1
            - 5: 0.1
            - 6: 0.1
            - 7: 0.1
            - 8: 0.1
            - 9: 0.1
            - 10: 0.1
            - 11: 0.1
            - 12: 0.1
            - 13: 0.1
            - 14: 0.1
            - 15: 0.1
            - 16: 0.1
            - 17: 0.1
            - 18: 0.1
            - 19: 0.1
            - 20: 0.1
            - 21: 0.1
            - 22: 0.1
            - 23: 0.1
            - 24: 0.1
          - holiday:
          - 1: 0.1
          - 2: 0.1
          - 3: 0.1
          - 4: 0.1
          - 5: 0.1
          - 6: 0.1
          - 7: 0.1
          - 8: 0.1
          - 9: 0.1
          - 10: 0.1
          - 11: 0.1
          - 12: 0.1
          - 13: 0.1
          - 14: 0.1
          - 15: 0.1
          - 16: 0.1
          - 17: 0.1
          - 18: 0.1
          - 19: 0.1
          - 20: 0.1
          - 21: 0.1
          - 22: 0.1
          - 23: 0.1
          - 24: 0.1
        - popdensdaytime:
          - working day: 100
          - holiday: 100
        - popdensnighttime:
          - working day: 100
          - holiday: 100
        - popprof_24hr:
          - working day:
            - 1: 100
            - 2: 100
            - 3: 100
            - 4: 100
            - 5: 100
            - 6: 100
            - 7: 100
            - 8: 100
            - 9: 100
            - 10: 100
            - 11: 100
            - 12: 100
            - 13: 100
            - 14: 100
            - 15: 100
            - 16: 100
            - 17: 100
            - 18: 100
            - 19: 100
            - 20: 100
            - 21: 100
            - 22: 100
            - 23: 100
            - 24: 100
          - holiday:
            - 1: 100
            - 2: 100
            - 3: 100
            - 4: 100
            - 5: 100
            - 6: 100
            - 7: 100
            - 8: 100
            - 9: 100
            - 10: 100
            - 11: 100
            - 12: 100
            - 13: 100
            - 14: 100
            - 15: 100
            - 16: 100
            - 17: 100
            - 18: 100
            - 19: 100
            - 20: 100
            - 21: 100
            - 22: 100
            - 23: 100
            - 24: 100
      - co2:
        - co2pointsource: 0.1
        - ef_umolco2perj: 0.1
        - enef_v_jkm: 0.1
        - fcef_v_kgkm: 0.1
        - frfossilfuel_heat: 0.1
        - frfossilfuel_nonheat: 0.1
        - maxfcmetab: 0.1
        - maxqfmetab: 0.1
        - min_res_bioco2: 0.1
        - minfcmetab: 0.1
        - minqfmetab: 0.1
        - trafficrate: 0.1
        - trafficunits: 0.1
        - traffprof_24hr:
          - working day:
            - 1: 0.1
            - 2: 0.1
            - 3: 0.1
            - 4: 0.1
            - 5: 0.1
            - 6: 0.1
            - 7: 0.1
            - 8: 0.1
            - 9: 0.1
            - 10: 0.1
            - 11: 0.1
            - 12: 0.1
            - 13: 0.1
            - 14: 0.1
            - 15: 0.1
            - 16: 0.1
            - 17: 0.1
            - 18: 0.1
            - 19: 0.1
            - 20: 0.1
            - 21: 0.1
            - 22: 0.1
            - 23: 0.1
            - 24: 0.1
          - holiday:
          - 1: 0.1
          - 2: 0.1
          - 3: 0.1
          - 4: 0.1
          - 5: 0.1
          - 6: 0.1
          - 7: 0.1
          - 8: 0.1
          - 9: 0.1
          - 10: 0.1
          - 11: 0.1
          - 12: 0.1
          - 13: 0.1
          - 14: 0.1
          - 15: 0.1
          - 16: 0.1
          - 17: 0.1
          - 18: 0.1
          - 19: 0.1
          - 20: 0.1
          - 21: 0.1
          - 22: 0.1
          - 23: 0.1
          - 24: 0.1
        - humactivity_24hr:
          - working day: # 24 hours
            - 1: 0.1
            - 2: 0.1
            - 3: 0.1
            - 4: 0.1
            - 5: 0.1
            - 6: 0.1
            - 7: 0.1
            - 8: 0.1
            - 9: 0.1
            - 10: 0.1
            - 11: 0.1
            - 12: 0.1
            - 13: 0.1
            - 14: 0.1
            - 15: 0.1
            - 16: 0.1
            - 17: 0.1
            - 18: 0.1
            - 19: 0.1
            - 20: 0.1
            - 21: 0.1
            - 22: 0.1
            - 23: 0.1
            - 24: 0.1
          - holiday:
          - 1: 0.1
          - 2: 0.1
          - 3: 0.1
          - 4: 0.1
          - 5: 0.1
          - 6: 0.1
          - 7: 0.1
          - 8: 0.1
          - 9: 0.1
          - 10: 0.1
          - 11: 0.1
          - 12: 0.1
          - 13: 0.1
          - 14: 0.1
          - 15: 0.1
          - 16: 0.1
          - 17: 0.1
          - 18: 0.1
          - 19: 0.1
          - 20: 0.1
          - 21: 0.1
          - 22: 0.1
          - 23: 0.1
          - 24: 0.1


  - initial states:
    - paved:
      - several properties
    - bldgs:
      - several properties
    - dectr:
      - decidcap_id: 1
      - several properties
    - snow:
      - several properties
    - vegetation:
      - several properties
    - building:
      - several properties
    - paved:
      - several properties
    - water:
      - several properties

